=== KeyWorksRW/wxUiEditor/src/xml/gen.dtd
<!ELEMENT GeneratorDefinitions ANY>

<!ELEMENT gen ANY>
    <!ATTLIST gen
        class CDATA #REQUIRED
        type CDATA #REQUIRED
    >
    <!ATTLIST gen
        image CDATA #IMPLIED
        flags CDATA #IMPLIED
    >

<!ELEMENT inherits ANY>
    <!ATTLIST inherits class CDATA #REQUIRED>

<!ELEMENT property ANY>
    <!ATTLIST property name CDATA #REQUIRED>
    <!ATTLIST property type (animation | bitlist | bitmap | bool | editoption | file | float | id | image | int | option | path | string | string_edit | string_edit_escapes | string_edit_single | string_escapes | stringlist | uint | uintlist | uintpairlist | wxColour | wxFont | wxPoint | wxSize) #REQUIRED>
    <!ATTLIST property help CDATA #IMPLIED>

<!ELEMENT option ANY>
    <!ATTLIST option name CDATA #REQUIRED>
    <!ATTLIST option help CDATA #IMPLIED>

<!ELEMENT event ANY>
    <!ATTLIST event
        name CDATA #REQUIRED
        class CDATA #REQUIRED
    >
    <!ATTLIST event help CDATA #IMPLIED>

<!ELEMENT category ANY>
    <!ATTLIST category name CDATA #REQUIRED>
    <!ATTLIST category base_name CDATA #IMPLIED>

=== KeyWorksRW/wxUiEditor/src/xml/books_xml.xml
inline const char* books_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="wxChoicebook" image="wxChoicebook" type="choicebook">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_choicebook</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			protected:
		</property>
		<property name="persist_name" type="string"
			help="If a name is specified, wxPersistenceManager will be used to save/restore the currently selected page." />
		<property name="style" type="option">
			<option name="wxCHB_DEFAULT"
				help="Choose the default location for the labels depending on the current platform (but currently it's the same everywhere, namely wxCHB_TOP)." />
			<option name="wxCHB_TOP"
				help="Place labels above the page area." />
			<option name="wxCHB_LEFT"
				help="Place labels on the left side." />
			<option name="wxCHB_RIGHT"
				help="Place labels on the right side." />
			<option name="wxCHB_BOTTOM"
				help="Place labels below the page area." />
			wxCHB_DEFAULT
		</property>
		<event name="wxEVT_CHOICEBOOK_PAGE_CHANGED" class="wxBookCtrlEvent"
			help="The page selection was changed." />
		<event name="wxEVT_CHOICEBOOK_PAGE_CHANGING" class="wxBookCtrlEvent"
			help="The page selection is about to be changed. This event can be vetoed (using wxNotifyEvent::Veto())." />
	</gen>

	<gen class="wxListbook" image="wxListbook" type="listbook">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_listbook</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			protected:
		</property>
		<property name="display_images" type="bool"
			help="If true, will display an image on the tab in addition to any text.">0</property>
		<property name="image_size" type="wxSize"
			help="All tab images will be scaled to this size.">16, 16</property>
		<property name="persist_name" type="string"
			help="If a name is specified, wxPersistenceManager will be used to save/restore the currently selected page." />
		<property name="style" type="option">
			<option name="wxBK_DEFAULT"
				help="Default location for the labels depending on the current platform (left everywhere except Mac where it is top)." />
			<option name="wxBK_TOP"
				help="Place labels above the page area." />
			<option name="wxBK_LEFT"
				help="Place labels on the left side." />
			<option name="wxBK_RIGHT"
				help="Place labels on the right side." />
			<option name="wxBK_BOTTOM"
				help="Place labels below the page area." />
			wxBK_DEFAULT
		</property>
		<event name="wxEVT_LISTBOOK_PAGE_CHANGED" class="wxBookCtrlEvent"
			help="The page selection was changed." />
		<event name="wxEVT_LISTBOOK_PAGE_CHANGING" class="wxBookCtrlEvent"
			help="The page selection is about to be changed. This event can be vetoed." />
	</gen>

	<gen class="wxNotebook" image="wxNotebook" type="notebook">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_notebook</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			protected:
		</property>
		<property name="display_images" type="bool"
			help="If true, will display an image on the tab in addition to any text.">0</property>
		<property name="image_size" type="wxSize"
			help="All tab images will be scaled to this size.">16, 16</property>
		<property name="persist_name" type="string"
			help="If a name is specified, wxPersistenceManager will be used to save/restore the currently selected page." />
		<property name="tab_position" type="option">
			<option name="wxBK_DEFAULT"
				help="Default placement of tabs (currently top on all platforms)." />
			<option name="wxBK_TOP"
				help="Place tabs on the top side." />
			<option name="wxBK_BOTTOM"
				help="Place tabs under instead of above the book pages." />
			<option name="wxBK_LEFT"
				help="Place tabs on the left side." />
			<option name="wxBK_RIGHT"
				help="Place tabs on the right side." />
			wxBK_DEFAULT
		</property>
		<property name="style" type="bitlist">
			<option name="wxNB_FIXEDWIDTH"
				help="All tabs will have same width. (Windows only)" />
			<option name="wxNB_MULTILINE"
				help="There can be several rows of tabs. (Windows only)" />
			<option name="wxNB_NOPAGETHEME"
				help="Display a solid colour on notebook pages, and not a gradient, which can reduce performance. (Windows only)" />
		</property>
		<event name="wxEVT_NOTEBOOK_PAGE_CHANGED" class="wxBookCtrlEvent"
			help="The page selection was changed." />
		<event name="wxEVT_NOTEBOOK_PAGE_CHANGING" class="wxBookCtrlEvent"
			help="The page selection is about to be changed. This event can be vetoed." />
	</gen>

	<gen class="wxToolbook" image="wxToolbook" type="notebook">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_toolbook</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			protected:
		</property>
		<property name="image_size" type="wxSize"
			help="All tool images will be scaled to this size.">16, 16</property>
		<property name="style" type="bitlist">
			<option name="wxTBK_HORZ_LAYOUT"
				help="Shows the text and the icons alongside, not vertically stacked (only implement under Windows and GTK 2 platforms as it relies on wxTB_HORZ_LAYOUT flag support)." />
		</property>
		<event name="wxEVT_TOOLBOOK_PAGE_CHANGED" class="wxBookCtrlEvent"
			help="The page selection was changed." />
		<event name="wxEVT_TOOLBOOK_PAGE_CHANGING" class="wxBookCtrlEvent"
			help="The page selection is about to be changed. This event can be vetoed." />
	</gen>

	<gen class="wxTreebook" image="wxTreebook" type="notebook">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_treebook</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			protected:
		</property>
		<property name="display_images" type="bool"
			help="If true, will display an image on the tab in addition to any text.">0</property>
		<property name="image_size" type="wxSize"
			help="All tab images will be scaled to this size.">16, 16</property>
		<property name="persist_name" type="string"
			help="If a name is specified, wxPersistenceManager will be used to save/restore the currently selected page and the expand/collapse state of sub pages." />
		<property name="tab_position" type="option">
			<option name="wxBK_DEFAULT"
				help="Default placement of tab (currently, positioned on the left)." />
			<option name="wxBK_TOP"
				help="Place tab on the top side." />
			<option name="wxBK_BOTTOM"
				help="Place tab under instead of above the book pages." />
			<option name="wxBK_LEFT"
				help="Place tabs on the left side." />
			<option name="wxBK_RIGHT"
				help="Place tab on the right side." />
			wxBK_DEFAULT
		</property>
		<property name="style" type="bitlist">
			<option name="wxNB_NOPAGETHEME"
				help="Display a solid colour on treebook pages, and not a gradient, which can reduce performance. (Windows only)" />
		</property>
		<event name="wxEVT_TREEBOOK_PAGE_CHANGED" class="wxBookCtrlEvent"
			help="The page selection was changed." />
		<event name="wxEVT_TREEBOOK_PAGE_CHANGING" class="wxBookCtrlEvent"
			help="The page selection is about to be changed. This event can be vetoed." />
		<event name="wxEVT_TREEBOOK_NODE_COLLAPSED" class="wxBookCtrlEvent"
			help="Generated when the page node is going to be collapsed." />
		<event name="wxEVT_TREEBOOK_NODE_EXPANDED" class="wxBookCtrlEvent"
			help="Generated when the page node is going to be collapsed." />
	</gen>

	<gen class="wxSimplebook" image="wxSimplebook" type="simplebook">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<property name="var_name" type="string">m_simplebook</property>
		<event name="wxEVT_BOOKCTRL_PAGE_CHANGED" class="wxBookCtrlEvent"
			help="The page selection was changed." />
		<event name="wxEVT_BOOKCTRL_PAGE_CHANGING" class="wxBookCtrlEvent"
			help="The page selection is about to be changed. This event can be vetoed." />
	</gen>

	<gen class="BookPage" image="book_page" type="bookpage">
		<inherits class="Window Events" />
		<inherits class="wxWindow">
			<property name="window_style" type="bitlist">wxTAB_TRAVERSAL</property>
		</inherits>
		<inherits class="sizer_child" />
		<property name="var_name" type="string">page</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			none
		</property>
		<property name="label" type="string_escapes">page</property>
		<property name="select" type="bool"
			help="Select Page when Adding">0</property>
		<property name="bitmap" type="image"
			help="Page Image (not all books use this)" />
	</gen>

	<gen class="PageCtrl" image="pagectrl" type="page">
		<property name="label" type="string_escapes">page</property>
		<property name="select" type="bool"
			help="Select Page when Adding">0</property>
		<property name="bitmap" type="image"
			help="Page Image (optional)" />
	</gen>

	<!-- wxFormBuilder import only -->

	<gen class="oldbookpage" type="oldbookpage">
		<property name="label" type="string_escapes" />
		<property name="bitmap" type="image" />
		<property name="select" type="bool" />
	</gen>
</GeneratorDefinitions>)===";

=== KeyWorksRW/wxUiEditor/src/xml/sizer_child_xml.xml
inline const char* sizer_child_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="sizer_child" type="interface">
		<property name="alignment" type="bitlist">
			<option name="wxALIGN_LEFT"
				help="Align the item to the left of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_TOP"
				help="Align the item to the top of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_RIGHT"
				help="Align the item to the right of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_BOTTOM"
				help="Align the item to the bottom of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_CENTER"
				help="Align the item to the center of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_CENTER_HORIZONTAL"
				help="Align the item to the horizontal center of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_CENTER_VERTICAL"
				help="Align the item to the vertical center of the space allotted to it by the sizer, adjusted for the border if any." />
		</property>
		<property name="borders" type="bitlist">
			<option name="wxALL"
				help="Enable all borders" />
			<option name="wxLEFT"
				help="Enable the left border" />
			<option name="wxRIGHT"
				help="Enable the right border" />
			<option name="wxTOP"
				help="Enable the top border" />
			<option name="wxBOTTOM"
				help="Enable the bottom border" />
			wxALL
		</property>
		<property name="border_size" type="uint"
			help="Sets the border size, if the flag parameter is set to include any border flag. The default value of 5 will be scaled on high DPI displayes.">5</property>
		<property name="flags" type="bitlist">
			<option name="wxEXPAND"
				help="The item will be expanded to fill the space assigned to the item." />
			<option name="wxSHAPED"
				help="The item will be expanded as much as possible while also maintaining its aspect ratio." />
			<option name="wxFIXED_MINSIZE"
				help="Normally wxSizers will use GetAdjustedBestSize to determine what the minimal size of window items should be, and will use that size to calculate the layout. This allows layouts to adjust when an item changes and its best size becomes different. If you would rather have a window item stay the size it started with then use wxFIXED_MINSIZE." />
			<option name="wxRESERVE_SPACE_EVEN_IF_HIDDEN"
				help="Normally wxSizers don't allocate space for hidden windows or other items. This flag overrides this behaviour so that sufficient space is allocated for the window even if it isn't visible. This makes it possible to dynamically show and hide controls without resizing the parent window." />
		</property>
		<property name="proportion" type="uint"
			help="How much this control will stretch in proportion to the other controls in the same sizer. Set to 0 to prevent stretching.">0</property>
		<property name="row" type="int"
			help="Row for the item.">0</property>
		<property name="column" type="int"
			help="Column for the item.">0</property>
		<property name="rowspan" type="int"
			help="The number of rows that the item spans.">1</property>
		<property name="colspan" type="int"
			help="The number of columns that the item spans.">1</property>
	</gen>
	<gen class="sizer_dimension" type="interface">
		<property name="minimum_size" type="wxSize"
			help="Normally, the sizer will calculate its minimal size based purely on how much space its children need. If the minimal size is > 0, 'GetMinSize' will return either the minimal size as requested by its children or the minimal size set here, depending on which is bigger." />
	</gen>

	<gen class="sizeritem_settings" type="interface">
		<property name="alignment" type="bitlist">
			<option name="wxALIGN_LEFT"
				help="Align the item to the left of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_TOP"
				help="Align the item to the top of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_RIGHT"
				help="Align the item to the right of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_BOTTOM"
				help="Align the item to the bottom of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_CENTER"
				help="Align the item to the center of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_CENTER_HORIZONTAL"
				help="Align the item to the horizontal center of the space allotted to it by the sizer, adjusted for the border if any." />
			<option name="wxALIGN_CENTER_VERTICAL"
				help="Align the item to the vertical center of the space allotted to it by the sizer, adjusted for the border if any." />
		</property>
		<property name="borders" type="bitlist">
			<option name="wxALL"
				help="Enable all borders" />
			<option name="wxLEFT"
				help="Enable the left border" />
			<option name="wxRIGHT"
				help="Enable the right border" />
			<option name="wxTOP"
				help="Enable the top border" />
			<option name="wxBOTTOM"
				help="Enable the bottom border" />
			wxALL
		</property>
		<property name="border_size" type="uint"
			help="Sets the border size, if the flag parameter is set to include any border flag. The default value of 5 will be scaled on high DPI displayes.">5</property>
		<property name="flags" type="bitlist">
			<option name="wxEXPAND"
				help="The item will be expanded to fill the space assigned to the item." />
			<option name="wxSHAPED"
				help="The item will be expanded as much as possible while also maintaining its aspect ratio." />
			<option name="wxFIXED_MINSIZE"
				help="Normally wxSizers will use GetAdjustedBestSize to determine what the minimal size of window items should be, and will use that size to calculate the layout. This allows layouts to adjust when an item changes and its best size becomes different. If you would rather have a window item stay the size it started with then use wxFIXED_MINSIZE." />
			<option name="wxRESERVE_SPACE_EVEN_IF_HIDDEN"
				help="Normally wxSizers don't allocate space for hidden windows or other items. This flag overrides this behaviour so that sufficient space is allocated for the window even if it isn't visible. This makes it possible to dynamically show and hide controls without resizing the parent window." />
		</property>
	</gen>

	<gen class="flexgridsizerbase" image="flex_grid_sizer" type="interface">
		<property name="vgap" type="uint"
			help="The vertical gap (in pixels) between the cells in the sizer.">0</property>
		<property name="hgap" type="uint"
			help="The horizontal gap (in pixels) between cells in the sizer.">0</property>
		<property name="growablerows" type="uintpairlist"
			help="Comma separated list of row indices (starting from zero, optional proportion appended after a colon) that should be grown if there is extra space available to the sizer." />
		<property name="growablecols" type="uintpairlist"
			help="Comma separated list of column indices (starting from zero, optional proportion appended after a colon) that should be grown if there is extra space available to the sizer." />
		<property name="flexible_direction" type="option"
			help="wxFlexGridSizer can size items equally in one direction but unequally ('flexibly') in the other">
			<option name="wxVERTICAL"
				help="Rows are flexibly sized." />
			<option name="wxHORIZONTAL"
				help="Columns are flexibly sized." />
			<option name="wxBOTH"
				help="Both rows and columns are flexibly sized (this is the default value)." />
			wxBOTH
		</property>
		<property name="non_flexible_grow_mode" type="option"
			help="If the sizer is only flexible in one direction (this can be changed using 'flexible_direction'), it needs to be decided how the sizer should grow in the other ('non flexible') direction in order to fill the available space.">
			<option name="wxFLEX_GROWMODE_NONE"
				help="Sizer doesn't grow in the non flexible direction." />
			<option name="wxFLEX_GROWMODE_SPECIFIED"
				help="Sizer honors growable columns/rows set with AddGrowableCol and AddGrowableRow. In this case equal sizing applies to minimum sizes of columns or rows (this is the default value)." />
			<option name="wxFLEX_GROWMODE_ALL"
				help="Sizer equally stretches all columns or rows in the non flexible direction, whether they are growable or not in the flexible direction." />
			wxFLEX_GROWMODE_SPECIFIED
		</property>
	</gen>
</GeneratorDefinitions>)===";

=== KeyWorksRW/wxUiEditor/src/xml/validators_xml.xml
inline const char* validators_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="Text Validator" type="interface">
		<property name="validator_variable" type="string"
			help="Name of a member variable associated with the validator" />
		<property name="validator_type" type="option"
			help="Type of a validator assigned to the window">
			<option name="wxTextValidator"
				help="Use this to transfer data to/from a wxString variable." />
			<option name="wxGenericValidator"
				help="Use this if you need to use something besides a wxString." />
			wxTextValidator
		</property>
		<property name="validator_data_type" type="option"
			help="Data type of the member variable">
			<option name="wxString"
				help="String value." />
			<option name="wxFileName"
				help="Only use this with a wxGenericValidator type." />
			<option name="int"
				help="Only use this with a wxGenericValidator type." />
			<option name="double"
				help="Only use this with a wxGenericValidator type." />
			<option name="float"
				help="Only use this with a wxGenericValidator type." />
			wxString
		</property>
		<property name="get_function" type="string"
			help="Function name to get the value of the variable." />
		<property name="set_function" type="string"
			help="Function name to set the value of the variable." />
		<property name="validator_style" type="bitlist"
			help="Data filtering style for wxTextValidator or wxGenericValidator.">
			<option name="wxFILTER_NONE"
				help="No filtering takes place." />
			<option name="wxFILTER_ASCII"
				help="Non-ASCII characters are filtered out." />
			<option name="wxFILTER_ALPHA"
				help="Non-alpha characters are filtered out." />
			<option name="wxFILTER_ALPHANUMERIC"
				help="Non-alphanumeric characters are filtered out." />
			<option name="wxFILTER_DIGITS"
				help="Non-numeric characters are filtered out. Uses isdigit() to perform the check." />
			<option name="wxFILTER_NUMERIC"
				help="Non-numeric characters are filtered out, but allows decimal points, minus/plus signs and the 'e' or 'E' character." />
			<option name="wxFILTER_INCLUDE_LIST"
				help="Use an include list. The validator checks if the user input is on the list, complaining if not. See wxTextValidator::SetIncludes." />
			<option name="wxFILTER_EXCLUDE_LIST"
				help="Use an exclude list. The validator checks if the user input is on the list, complaining if it is. See wxTextValidator::SetExcludes." />
			<option name="wxFILTER_INCLUDE_CHAR_LIST"
				help="Use an include list. The validator checks if each input character is in the list (one character per list element), complaining if not. See wxTextValidator::SetIncludes." />
			<option name="wxFILTER_EXCLUDE_CHAR_LIST"
				help="Use an include list. The validator checks if each input character is in the list (one character per list element), complaining if it is. See wxTextValidator::SetExcludes." />
			wxFILTER_NONE
		</property>
	</gen>

	<gen class="Boolean Validator" type="interface">
		<property name="validator_variable" type="string"
			help="Name of a member variable associated with the validator" />
		<property name="validator_data_type" type="option"
			help="Data type of the member variable">
			<option name="bool"
				help="Boolean value." />
			bool
		</property>
		<property name="get_function" type="string"
			help="Function name to get the value of the variable." />
		<property name="set_function" type="string"
			help="Function name to set the value of the variable." />
	</gen>

	<gen class="Integer Validator" type="interface">
		<property name="validator_variable" type="string"
			help="Name of a member variable associated with the validator" />
		<property name="validator_data_type" type="option"
			help="Data type of the member variable">
			<option name="int"
				help="Integer value." />
			int
		</property>
		<property name="get_function" type="string"
			help="Function name to get the value of the variable." />
		<property name="set_function" type="string"
			help="Function name to set the value of the variable." />
	</gen>

	<gen class="Choice Validator" type="interface">
		<property name="validator_variable" type="string"
			help="Name of a member variable associated with the validator" />
		<property name="validator_data_type" type="option"
			help="Data type of the member variable">
			<option name="wxString"
				help="String value." />
			<option name="int"
				help="Integer value." />
			wxString
		</property>
		<property name="get_function" type="string"
			help="Function name to get the value of the variable." />
		<property name="set_function" type="string"
			help="Function name to set the value of the variable." />
	</gen>

	<gen class="String Validator" type="interface">
		<property name="validator_variable" type="string"
			help="Name of a member variable associated with the validator" />
		<property name="validator_data_type" type="option"
			help="Data type of the member variable">
			<option name="wxString"
				help="String value." />
			wxString
		</property>
		<property name="get_function" type="string"
			help="Function name to get the value of the variable." />
		<property name="set_function" type="string"
			help="Function name to set the value of the variable." />
	</gen>

	<gen class="List Validator" type="interface">
		<property name="validator_variable" type="string"
			help="Name of a member variable associated with the validator" />
		<property name="validator_data_type" type="option"
			help="Data type of the member variable">
			<option name="wxArrayInt"
				help="Integer value." />
			wxArrayInt
		</property>
		<property name="get_function" type="string"
			help="Function name to get the value of the variable." />
		<property name="set_function" type="string"
			help="Function name to set the value of the variable." />
	</gen>
</GeneratorDefinitions>)===";
