=== KeyWorksRW/wxUiEditor/src/xml/gen.dtd
<!ELEMENT GeneratorDefinitions ANY>

<!ELEMENT gen ANY>
    <!ATTLIST gen
        class CDATA #REQUIRED
        type CDATA #REQUIRED
    >
    <!ATTLIST gen
        image CDATA #IMPLIED
        flags CDATA #IMPLIED
    >

<!ELEMENT inherits ANY>
    <!ATTLIST inherits class CDATA #REQUIRED>

<!ELEMENT property ANY>
    <!ATTLIST property name CDATA #REQUIRED>
    <!ATTLIST property type (animation | bitlist | bitmap | bool | editoption | file | float | id | image | int | option | path | string | string_edit | string_edit_escapes | string_edit_single | string_escapes | stringlist | uint | uintlist | uintpairlist | wxColour | wxFont | wxPoint | wxSize) #REQUIRED>
    <!ATTLIST property help CDATA #IMPLIED>

<!ELEMENT option ANY>
    <!ATTLIST option name CDATA #REQUIRED>
    <!ATTLIST option help CDATA #IMPLIED>

<!ELEMENT event ANY>
    <!ATTLIST event
        name CDATA #REQUIRED
        class CDATA #REQUIRED
    >
    <!ATTLIST event help CDATA #IMPLIED>

<!ELEMENT category ANY>
    <!ATTLIST category name CDATA #REQUIRED>
    <!ATTLIST category base_name CDATA #IMPLIED>

=== KeyWorksRW/wxUiEditor/src/xml/bars_xml.xml
inline const char* bars_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="wxStatusBar" image="statusbar" type="statusbar">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<property name="var_name" type="string">m_statusBar</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			protected:
		</property>
		<property name="fields" type="uint"
			help="Number of fields in the statusbar.">1</property>
		<property name="style" type="bitlist">
			<option name="wxSTB_SIZEGRIP"
				help="Displays a gripper at the right-hand side of the status bar which can be used to resize the parent window." />
			<option name="wxSTB_SHOW_TIPS"
				help="Displays tooltips for those panes whose status text has been ellipsized/truncated because the status text doesn't fit the pane width. Note that this style has effect only on wxGTK (with GTK+ >= 2.12) currently." />
			<option name="wxSTB_ELLIPSIZE_START"
				help="Replace the beginning of the status texts with an ellipsis when the status text widths exceed the status bar pane's widths (uses wxControl::Ellipsize)." />
			<option name="wxSTB_ELLIPSIZE_MIDDLE"
				help="Replace the middle of the status texts with an ellipsis when the status text widths exceed the status bar pane's widths (uses wxControl::Ellipsize)." />
			<option name="wxSTB_ELLIPSIZE_END"
				help="Replace the end of the status texts with an ellipsis when the status text widths exceed the status bar pane's widths (uses wxControl::Ellipsize)." />
			<option name="wxSTB_DEFAULT_STYLE"
				help="The default style: includes wxSTB_SIZEGRIP | wxSTB_SHOW_TIPS | wxSTB_ELLIPSIZE_END | wxFULL_REPAINT_ON_RESIZE" />
			wxSTB_DEFAULT_STYLE
		</property>
	</gen>

	<gen class="wxInfoBar" image="infobar" type="widget">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_infoBar</property>
		<property name="show_effect" type="option"
			help="Set the effects to use when showing the bar.">
			<option name="wxSHOW_EFFECT_NONE"
				help="No effect, equivalent to normal wxWindow::Show() or Hide() call." />
			<option name="wxSHOW_EFFECT_ROLL_TO_LEFT"
				help="Roll window to the left." />
			<option name="wxSHOW_EFFECT_ROLL_TO_RIGHT"
				help="Roll window to the right." />
			<option name="wxSHOW_EFFECT_ROLL_TO_TOP"
				help="Roll window to the top." />
			<option name="wxSHOW_EFFECT_ROLL_TO_BOTTOM"
				help="Roll window to the bottom." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_LEFT"
				help="Slide window to the left." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_RIGHT"
				help="Slide window to the right." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_TOP"
				help="Slide window to the top." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_BOTTOM"
				help="Slide window to the bottom." />
			<option name="wxSHOW_EFFECT_BLEND"
				help="Fade in or out effect." />
			<option name="wxSHOW_EFFECT_EXPAND"
				help="Expanding or collapsing effect." />
			wxSHOW_EFFECT_NONE
		</property>
		<property name="hide_effect" type="option"
			help="Set the effects to use when hiding the bar. ">
			<option name="wxSHOW_EFFECT_NONE"
				help="No effect, equivalent to normal wxWindow::Show() or Hide() call." />
			<option name="wxSHOW_EFFECT_ROLL_TO_LEFT"
				help="Roll window to the left." />
			<option name="wxSHOW_EFFECT_ROLL_TO_RIGHT"
				help="Roll window to the right." />
			<option name="wxSHOW_EFFECT_ROLL_TO_TOP"
				help="Roll window to the top." />
			<option name="wxSHOW_EFFECT_ROLL_TO_BOTTOM"
				help="Roll window to the bottom." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_LEFT"
				help="Slide window to the left." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_RIGHT"
				help="Slide window to the right." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_TOP"
				help="Slide window to the top." />
			<option name="wxSHOW_EFFECT_SLIDE_TO_BOTTOM"
				help="Slide window to the bottom." />
			<option name="wxSHOW_EFFECT_BLEND"
				help="Fade in or out effect." />
			<option name="wxSHOW_EFFECT_EXPAND"
				help="Expanding or collapsing effect." />
			wxSHOW_EFFECT_NONE
		</property>
		<property name="duration" type="int"
			help="Set the duration of the animation (in milliseconds) used when showing or hiding the bar.">500</property>
	</gen>
</GeneratorDefinitions>)===";

=== KeyWorksRW/wxUiEditor/src/xml/project_xml.xml
inline const char* project_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="Project" type="project" image="project">
		<inherits class="C++" />
		<inherits class="wxPython" />
		<inherits class="wxRuby" />
		<inherits class="wxGo" />
		<inherits class="wxLua" />
		<inherits class="wxPerl" />
		<inherits class="wxRust" />
		<inherits class="XRC" />
		<property name="code_preference" type="option"
			help="Specify the code you prefer to generate. This can affect default settings for variable names, various initial UI states, and the UI display in the Mockup panel.">
			<option name="C++" />
			<option name="Python" />
			<option name="Ruby" />
			<option name="XRC" />
			C++
		</property>
		<property name="art_directory" type="path"
			help="The directory containing your images (png, ico, xpm, etc.).">./</property>
		<property name="internationalize" type="bool"
			help="Wrap strings in a _() macro.">0</property>
		<property name="help_provider" type="option"
			help="The class of help provider to use for context-sensitive help.">
			<option name="none"
				help="No support for context-sensitive help." />
			<option name="wxSimpleHelpProvider"
				help="Use wxSimpleHelpProvider to provide context-sensitive help." />
			<option name="wxHelpControllerHelpProvider"
				help="Use wxHelpControllerHelpProvider to provide context-sensitive help." />
			none
		</property>
		<property name="id_prefixes" type="stringlist_semi"
			help="Optional prefixes to apply before a custom id. These can be added in the ID Editor dialog." />
		<property name="id_suffixes" type="stringlist_semi"
			help="Optional suffixes to apply after a custom id. These can be added in the ID Editor dialog." />
	</gen>

	<gen class="folder" image="folder" type="folder">
		<inherits class="Folder C++ Overrides" />
		<inherits class="Folder wxPython Overrides" />
		<inherits class="Folder wxRuby Overrides" />
		<inherits class="Folder XRC Overrides" />
		<property name="label" type="string"
			help="The name of the folder.">my_forms</property>
		<property name="code_preference" type="option"
			help="Specify the code you prefer to generate. This can affect default settings for variable names, various initial UI states, and the UI display in the Mockup panel.">
			<option name="C++" />
			<option name="Python" />
			<option name="Ruby" />
			<option name="XRC" />
			C++
		</property>
	</gen>

	<gen class="sub_folder" image="folder" type="sub_folder">
		<property name="label" type="string"
			help="The name of the folder.">my_forms</property>
	</gen>
</GeneratorDefinitions>)===";

=== KeyWorksRW/wxUiEditor/src/xml/grid_xml.xml
inline const char* grid_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="wxGrid" image="grid" type="widget">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_grid</property>
		<property name="class_access" type="option">
			<option name="none" />
			<option name="protected:" />
			<option name="public:" />
			protected:
		</property>
		<property name="rows" type="uint"
			help="Number of Rows.">5</property>
		<property name="cols" type="uint"
			help="Number of Columns.">5</property>
		<property name="editing" type="bool"
			help="Allow editing grid contents.">1</property>
		<property name="grid_lines" type="bool"
			help="Show grid lines.">1</property>
		<property name="grid_line_color" type="wxColour"
			help="The colour used to draw grid lines." />
		<property name="drag_grid_size" type="bool"
			help="Allow sizing rows and columns by dragging gridlines.">0</property>
		<property name="margin_width" type="uint"
			help="Sets the extra width to display arouned the grid.">0</property>
		<property name="margin_height" type="uint"
			help="Sets the extra height to displaye around the grid.">0</property>
		<property name="selection_mode" type="option">
			<option name="wxGridSelectCells"
				help="Select individual cells as well as of the entire rows and columns. This is the default." />
			<option name="wxGridSelectColumns"
				help="Select entire columns only." />
			<option name="wxGridSelectRows"
				help="Select entire rows only." />
			<option name="wxGridSelectRowsOrColumns"
				help="Select either the entire columns or the entire rows but not individual cells nor blocks." />
			<option name="wxGridSelectNone"
				help="No selections can be made. The user won't be able to select any cells in this mode. Available since dgets 3.1.5" />
			wxGridSelectCells
		</property>

		<category name="Labels">
			<property name="native_col_header" type="bool"
				help="If true, a wxHeaderCtrl is used instead to display the column labels instead of drawing them in wxGrid code itself.">0</property>
			<property name="native_col_labels" type="bool"
				help="If true, column labels use a native look by calling wxRendererNative::DrawHeaderButton() internally. This option is ignored if native_col_header is set to true." />
			<property name="label_bg" type="wxColour"
				help="Background color for row and column labels." />
			<property name="label_font" type="wxFont"
				help="Font for row and column labels." />
			<property name="label_text" type="wxColour"
				help="Colour for row and column label text." />
		</category>

		<category name="Cells">
			<property name="cell_bg" type="wxColour"
				help="Default cell background color." />
			<property name="cell_font" type="wxFont"
				help="Default cell font." />
			<property name="cell_text" type="wxColour"
				help="Default cell text color." />
			<property name="cell_horiz_alignment" type="option"
				help="Default horizontal alignment of cell values.">
				<option name="wxALIGN_LEFT"
					help="Align left." />
				<option name="wxALIGN_CENTER"
					help="Align centered." />
				<option name="wxALIGN_RIGHT"
					help="Align right." />
				wxALIGN_LEFT
			</property>
			<property name="cell_vert_alignment" type="option"
				help="Default vertical alignment of cell values.">
				<option name="wxALIGN_TOP"
					help="Align top." />
				<option name="wxALIGN_CENTER"
					help="Align centered." />
				<option name="wxALIGN_BOTTOM"
					help="Align bottom." />
				wxALIGN_TOP
			</property>
		</category>

		<category name="Columns">
			<property name="col_label_values" type="stringlist"
				help="List of column labels." />
			<property name="default_col_size" type="int"
				help="Sets the default width for columns in the grid. Ignored unless a positive value is set.">-1</property>
			<property name="autosize_cols" type="bool"
				help="Automatically sizes all columns to fit their contents. Ignored if default_col_size is set to a positive value">0</property>
			<property name="drag_col_move" type="bool"
				help="Allow moving columns by dragging.">0</property>
			<property name="drag_col_size" type="bool"
				help="Allow sizing columns by dragging.">1</property>
			<property name="col_label_size" type="int"
				help="Height of column labels. If height equals -1 then height is calculated automatically so that no label is truncated.">-1</property>
			<property name="col_label_horiz_alignment" type="option"
				help="Horizontal alignment of column label text.">
				<option name="wxALIGN_LEFT"
					help="Align labels left." />
				<option name="wxALIGN_CENTER"
					help="Align labels centered." />
				<option name="wxALIGN_RIGHT"
					help="Align labels right." />
				wxALIGN_CENTER
			</property>
			<property name="col_label_vert_alignment" type="option"
				help="Vertical alignment of column label text.">
				<option name="wxALIGN_TOP"
					help="Align labels top." />
				<option name="wxALIGN_CENTER"
					help="Align labels centered." />
				<option name="wxALIGN_BOTTOM"
					help="Align labels bottom." />
				wxALIGN_CENTER
			</property>
		</category>

		<category name="Rows">
			<property name="row_label_values" type="stringlist"
				help="List of row labels." />
			<property name="default_row_size" type="int"
				help="Sets the default height for rows in the grid. Ignored unless a positive value is set.">-1</property>
			<property name="autosize_rows" type="bool"
				help="Automatically sizes all rows to fit their contents. Ignored if default_row_size is set to a positive value">0</property>
			<property name="drag_row_size" type="bool"
				help="Allow sizing rows by dragging with the mouse.">1</property>
			<property name="row_label_size" type="int"
				help="Width of row labels. If width equals -1 then width is calculated automatically so that no label is truncated.">-1</property>
			<property name="row_label_horiz_alignment" type="option"
				help="Horizontal alignment of row label text.">
				<option name="wxALIGN_LEFT"
					help="Align labels left." />
				<option name="wxALIGN_CENTER"
					help="Align labels centered." />
				<option name="wxALIGN_RIGHT"
					help="Align labels right." />
				wxALIGN_CENTER
			</property>
			<property name="row_label_vert_alignment" type="option"
				help="Vertical alignment of row label text.">
				<option name="wxALIGN_TOP"
					help="Align labels top." />
				<option name="wxALIGN_CENTER"
					help="Align labels centered." />
				<option name="wxALIGN_BOTTOM"
					help="Align labels bottom." />
				wxALIGN_CENTER
			</property>
			<property name="tab_behaviour" type="option">
				<option name="Tab_Stop"
					help="Do nothing. This is the default." />
				<option name="Tab_Wrap"
					help="Move to the beginning of the next (or the end of the previous) row." />
				<option name="Tab_Leave"
					help="Move to the next (or the previous) control after the grid." />
				Tab_Stop
			</property>
		</category>

		<event name="wxEVT_GRID_CELL_LEFT_CLICK" class="wxGridEvent"
			help="The user clicked a cell with the left mouse button." />
		<event name="wxEVT_GRID_CELL_RIGHT_CLICK" class="wxGridEvent"
			help="The user clicked a cell with the right mouse button." />
		<event name="wxEVT_GRID_CELL_LEFT_DCLICK" class="wxGridEvent"
			help="The user double-clicked a cell with the left mouse button." />
		<event name="wxEVT_GRID_CELL_RIGHT_DCLICK" class="wxGridEvent"
			help="The user double-clicked a cell with the right mouse button." />
		<event name="wxEVT_GRID_LABEL_LEFT_CLICK" class="wxGridEvent"
			help="The user clicked a label with the left mouse button." />
		<event name="wxEVT_GRID_LABEL_RIGHT_CLICK" class="wxGridEvent"
			help="The user clicked a label with the right mouse button." />
		<event name="wxEVT_GRID_LABEL_LEFT_DCLICK" class="wxGridEvent"
			help="The user double-clicked a label with the left mouse button." />
		<event name="wxEVT_GRID_LABEL_RIGHT_DCLICK" class="wxGridEvent"
			help="The user double-clicked a label with the right mouse button." />
		<event name="wxEVT_GRID_CELL_CHANGED" class="wxGridEvent"
			help="The user changed the data in a cell." />
		<event name="wxEVT_GRID_SELECT_CELL" class="wxGridEvent"
			help="The user moved to, and selected a cell." />
		<event name="wxEVT_GRID_EDITOR_HIDDEN" class="wxGridEvent"
			help="The editor for a cell was hidden." />
		<event name="wxEVT_GRID_EDITOR_SHOWN" class="wxGridEvent"
			help="The editor for a cell was shown." />
		<event name="wxEVT_GRID_COL_SIZE" class="wxGridSizeEvent"
			help="The user resized a column by dragging it." />
		<event name="wxEVT_GRID_ROW_SIZE" class="wxGridSizeEvent"
			help="The user resized a row by dragging it." />
		<event name="wxEVT_GRID_RANGE_SELECT" class="wxGridRangeSelectEvent"
			help="The user selected a group of contiguous cells." />
		<event name="wxEVT_GRID_EDITOR_CREATED" class="wxGridEditorCreatedEvent"
			help="The editor for a cell was created." />
	</gen>
</GeneratorDefinitions>)===";

=== KeyWorksRW/wxUiEditor/src/xml/lang_settings.xml
inline const char* language_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="C++ Settings" type="interface">
		<property name="base_file" type="file"
			help="The filename of the base class." />
		<property name="generate_translation_unit" type="bool"
			help="If checked, both a source file (translation unit) and a header file are generated. If not checked, all code is generated in the header file, and no source file is created.">
			1</property>
		<property name="source_preamble" type="code_edit"
			help="This preamble is added in addition to any src_preamble specified for the entire project. It will be placed unchanged at the top of the generated base src file after any (optional) precompiled header file." />
		<property name="local_src_includes" type="include_files"
			help="Lists one or more local header files to include in the generated header file." />
		<property name="system_src_includes" type="include_files"
			help="Lists one or more system header files to include in the generated header file." />
		<property name="header_preamble" type="code_edit"
			help="This preamble is placed unchanged in the generated header file after all wx/ include files. It is commonly used to add forward class names needed by methods and members you add to the Derived Class Settings." />
		<property name="local_hdr_includes" type="include_files"
			help="Lists one or more local header files to include in the generated header file." />
		<property name="system_hdr_includes" type="include_files"
			help="Lists one or more system header files to include in the generated header file." />
		<property name="generate_ids" type="bool"
			help="If checked, any non-wxWidgets ids will be created as an enumerated list unless you specically assign the value of the id (e.g., myid=100).">
			1</property>
		<property name="initial_enum_string" type="string"
			help="The first id in a generated enum will be set to this value.">
			wxID_HIGHEST + 1</property>
		<property name="generate_const_values" type="bool"
			help="If checked, each form's header file will have const values declared for some of the possible parameters. E.g., const int form_id = your_id. You can use this when creating multiple instances of a form with different construction parameters.">
			0</property>
		<property name="class_decoration" type="string"
			help="This specifies the keyword or macro to add to the class declaration (such as __declspec(dllexport) )." />
	</gen>

	<gen class="C++ Derived Class Settings" type="interface">
		<property name="use_derived_class" type="bool"
			help="Check this if you will be creating a derived class. If not checked, you will need to create a source file implementing any event handlers.">
			1</property>
		<property name="derived_class_name" type="string"
			help="The name of the derived class. Ignored if use_derived_class is unchecked." />
		<property name="derived_file" type="file"
			help="The filename of the derived class. You can leave this empty if you have already generated the file. Ignored if use_derived_class is unchecked." />
		<property name="additional_inheritance" type="stringlist_escapes"
			help="Additional classes to inherit from (these can be your own classes if you specified their header file in base_hdr_includes in the C++ Settings section above)." />
		<property name="class_methods" type="stringlist_escapes"
			help="Additional class methods to add (useful if you are *not* using a derived class." />
		<property name="class_members" type="stringlist_escapes"
			help="Additional class variable members to add (useful if you are *not* using a derived class." />
		<property name="inserted_hdr_code" type="code_edit"
			help="Specify code to insert into the header file at the end of the public: section. You may add protected: and private: sections as needed for additional methods and member variables." />
		<property name="private_members" type="bool"
			help="Check this to make all protected: members private:. This can only be done if you are NOT creating a derived class (use_derived_class is unchecked)." />
	</gen>

	<gen class="wxPython Settings" type="interface">
		<property name="python_file" type="file"
			help="The filename to use if generating code for wxPython." />
		<property name="insert_python_code" type="code_edit"
			help="Specify the code to insert into the python file after the generated import statements. This is usually used to import addtional modules, but can be any valid python code for use before the class definition." />
		<!-- <property name="python_variable_args" type="bool"
			help="If checked, the form
		parameters will be set to (*args, **kwargs) instead of listing all the parameters and their
		default values.">1</property> -->
		<property name="python_inherit_name" type="string"
			help="The name to use for an inherited class. If specified, the Inherit tab in the Python panel will include a sample for creating an inherited class." />
	</gen>

	<gen class="wxPython Frame Settings" type="interface">
		<property name="python_file" type="file"
			help="The filename to use if generating code for wxPython." />
		<property name="import_all_dialogs" type="bool"
			help="If checked, every wxDialog or wxWizard in this project that has a python_file specified for it will be imported into this module.">
			0</property>
		<property name="insert_python_code" type="code_edit"
			help="Specify the code to insert into the python file after the generated import statements. This is usually used to import addtional modules, but can be any valid python code for use before the class definition." />
		<property name="python_inherit_name" type="string"
			help="The name to use for an inherited class. If specified, the Inherit tab in the Python panel will include a sample for creating an inherited class." />
	</gen>

	<gen class="XRC Settings" type="interface">
		<property name="xrc_file" type="file"
			help="The filename to use if generating XRC (wxPython can override this with its own file name)." />
		<property name="xrc_no_whitespace" type="bool"
			help="If checked, no leading whitespace will be used. This makes the file smaller, but less readable.">
			0</property>
	</gen>
</GeneratorDefinitions>)===";
