=== KeyWorksRW/wxUiEditor/src/xml/gen.dtd
<!ELEMENT GeneratorDefinitions ANY>

<!ELEMENT gen ANY>
    <!ATTLIST gen
        class CDATA #REQUIRED
        type CDATA #REQUIRED
    >
    <!ATTLIST gen
        image CDATA #IMPLIED
        flags CDATA #IMPLIED
    >

<!ELEMENT inherits ANY>
    <!ATTLIST inherits class CDATA #REQUIRED>

<!ELEMENT property ANY>
    <!ATTLIST property name CDATA #REQUIRED>
    <!ATTLIST property type (animation | bitlist | bitmap | bool | editoption | file | float | id | image | int | option | path | string | string_edit | string_edit_escapes | string_edit_single | string_escapes | stringlist | uint | uintlist | uintpairlist | wxColour | wxFont | wxPoint | wxSize) #REQUIRED>
    <!ATTLIST property help CDATA #IMPLIED>

<!ELEMENT option ANY>
    <!ATTLIST option name CDATA #REQUIRED>
    <!ATTLIST option help CDATA #IMPLIED>

<!ELEMENT event ANY>
    <!ATTLIST event
        name CDATA #REQUIRED
        class CDATA #REQUIRED
    >
    <!ATTLIST event help CDATA #IMPLIED>

<!ELEMENT category ANY>
    <!ATTLIST category name CDATA #REQUIRED>
    <!ATTLIST category base_name CDATA #IMPLIED>

=== KeyWorksRW/wxUiEditor/src/xml/project.xml
<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<!-- project_xml, objects_xml -->
<GeneratorDefinitions>
    <gen class="Project" type="project" image="project">
        <inherits class="C++"/>
        <inherits class="wxPython"/>
        <inherits class="wxRuby"/>
        <inherits class="kwxFortran"/>
        <inherits class="kwxGO"/>
        <inherits class="kwxLuaJIT"/>
        <inherits class="kwxJulia"/>
        <inherits class="kwxTypeScript"/>
        <inherits class="XRC"/>

        <property name="code_preference" type="option"
            help="Specify the code you prefer to generate. This can affect default settings for variable names, various initial UI states, and the UI display in the Mockup panel.">
            <option name="C++"/>
			<option name="Python"/>
			<option name="Ruby"/>
			<option name="Fortran"/>
			<option name="GO"/>
			<option name="LuaJIT"/>
			<option name="Julia"/>
			<option name="TypeScript"/>
		<option name="XRC"/>
            C++</property>
        <property name="generate_languages" type="bitlist"
            help="Specify the programming languages you might want to view or generate from this project. The code preference language above will always be available when this project is loaded.">
            <option name="C++"/>
			<option name="Python"/>
			<option name="Ruby"/>
			<option name="Fortran"/>
			<option name="GO"/>
			<option name="Julia"/>
			<option name="LuaJIT"/>
			<option name="TypeScript"/>
			<option name="XRC"/>
            C++
        </property>
        <property name="art_directory" type="path"
            help="The directory containing your images (png, ico, xpm, etc.).">./</property>
        <property name="dialog_units" type="bool"
            help="When checked, dimensions will default to using dialog units. You can turn on or off dialog units for each individual dimension -- this just sets the default for new dimensions.">
            1</property>
        <property name="internationalize" type="bool"
            help="Wrap strings in a _() macro.">0</property>
        <property name="help_provider" type="option"
            help="The class of help provider to use for context-sensitive help.">
            <option name="none"
                help="No support for context-sensitive help."/>
			<option name="wxSimpleHelpProvider"
                help="Use wxSimpleHelpProvider to provide context-sensitive help."/>
			<option
                name="wxHelpControllerHelpProvider"
                help="Use wxHelpControllerHelpProvider to provide context-sensitive help."/>none</property>
        <property name="id_prefixes" type="stringlist_semi"
            help="Optional prefixes to apply before a custom id. These can be added in the ID Editor dialog."/>
        <property name="id_suffixes" type="stringlist_semi"
            help="Optional suffixes to apply after a custom id. These can be added in the ID Editor dialog."/>
        <property name="optional_comments" type="bool"
            help="Add some explanatory comments to the generated code.">0</property>
    </gen>

    <gen class="folder" image="folder" type="folder">
        <inherits class="Folder C++ Overrides"/>
        <inherits class="Folder wxPython Overrides"/>
        <inherits class="Folder wxRuby Overrides"/>
        <inherits class="Folder XRC Overrides"/>
        <property name="label" type="string"
            help="The name of the folder.">my_forms</property>
        <property name="code_preference" type="option"
            help="Specify the code you prefer to generate. This can affect default settings for variable names, various initial UI states, and the UI display in the Mockup panel.">
            <option name="C++"/>
			<option name="Python"/>
			<option name="Ruby"/>
			<option name="GO"/>
			<option name="Fortran"/>
			<option name="Julia"/>
			<option name="LuaJIT"/>
			<option name="TypeScript"/>
			<option name="XRC"/>C++</property>
    </gen>

    <gen class="sub_folder" image="folder" type="sub_folder">
        <property name="label" type="string"
            help="The name of the folder.">my_forms</property>
    </gen>

    <gen class="Images" image="images" type="images">
        <property name="base_file" type="file"
            help="The C++ filename to store all the embedded images in.">my_images</property>
        <property name="python_file" type="file"
            help="The Python filename to store all the embedded images in.">images</property>
        <property name="ruby_file" type="file"
            help="The Ruby filename to store all the embedded images in.">images</property>
        <property name="add_externs" type="bool"
            help="If checked, each image data array will be added to the header file as an extern.">0</property>
        <property name="auto_add" type="bool"
            help="If checked, then whenever you add an image file to a control, it will automatically be added to the Images List.">0</property>
    </gen>

    <gen class="embedded_image" image="bitmap" type="embed_image">
        <property name="bitmap" type="image"/>
    </gen>

    <gen class="wxTimer" image="wxTimer" type="timer">
        <property name="var_name" type="string">m_timer</property>
        <property name="interval" type="int"
            help="Specifies the number of milliseconds between timer events.">1000</property>
        <property name="auto_start" type="bool"
            help="If checked, this will start start the timer in the parent class Create function.">0</property>
        <property name="one_shot" type="bool"
            help="If checked, this will start a one shot timer (ignored if auto_start isn't checked).">0</property>
        <property name="id" type="id"
            help="Specifies the timer's identifier.">wxID_ANY</property>
        <event name="wxEVT_TIMER" class="wxTimerEvent"
            help="Timer event that will be sent to the parent form's class."/>
    </gen>

    <gen class="Data" image="data_list" type="data_list">
        <property name="output_file" type="file"
            help="The C++ filename to store all the data strings in.">wxue_data</property>
        <!-- <property name="python_file" type="file"
            help="The Python filename to store all the data strings in.">wxue_data</property> -->
        <!-- <property name="ruby_file" type="file"
            help="The Ruby filename to store all the data strings in.">wxue_data</property> -->
    </gen>

    <gen class="data_folder" image="folder" type="data_folder">
        <property name="label" type="string"
            help="The name of the folder.">my_data_files</property>
        <!-- <property name="output_file" type="file"
			help="If specified, all items in this folder will be generated to this file instead of the main output file."/> -->
    </gen>

    <gen class="data_string" image="text_file" type="data_string">
        <property name="var_name" type="string">my_data_string</property>
        <property name="data_file" type="file"/>
        <property name="no_compression" type="bool"
            help="If checked, the file will not be compressed. Check this when adding a binary file that has already been
        compressed. If unchecked, the file will be compressed using zlib.">0</property>
    </gen>

    <gen class="data_xml" image="xml_file" type="data_string">
        <property name="var_name" type="string">my_xml_string</property>
        <property name="data_file" type="file"/>
        <property name="xml_condensed_format" type="bool"
            help="If checked, the file is parsed and rewritten, removing all line breaks, indetation and comments. This will speed up parsing if the string is passed to an XML parser.">
            1</property>
    </gen>

</GeneratorDefinitions>

=== KeyWorksRW/wxUiEditor/src/xml/containers_xml.xml
inline const char* containers_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="wxPanel" image="wxPanel" type="container">
		<inherits class="Window Events" />
		<inherits class="wxWindow">
			<property name="window_style" type="bitlist">wxTAB_TRAVERSAL</property>
		</inherits>
		<inherits class="sizer_child" />
		<property name="var_name" type="string">panel</property>
	</gen>

	<gen class="wxSplitterWindow" image="wxSplitterWindow" type="splitter">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_splitter</property>
		<property name="splitmode" type="option">
			<option name="wxSPLIT_VERTICAL"
				help="Specifies a vertical split window." />
			<option name="wxSPLIT_HORIZONTAL"
				help="Specifies a horizontal split window." />
			wxSPLIT_VERTICAL
		</property>
		<property name="sashpos" type="int"
			help="The initial sash position.">0</property>
		<property name="sashsize" type="int"
			help="Overrides platform metrics if greater than -1">-1</property>
		<property name="sashgravity" type="float"
			help="Sets the sash gravity. Gravity is real factor which controls position of sash while resizing wxSplitterWindow. Gravity tells wxSplitterWindow how much will left/top window grow while resizing.">0.0</property>
		<property name="min_pane_size" type="uint"
			help="Minimum size for the panes. A minimum less than 1 is not allowed in the designer, because the designer prevents un-splitting.">0</property>
		<property name="persist_name" type="string"
			help="If a name is specified, wxPersistenceManager will be used to save/restore the sash position." />
		<property name="style" type="bitlist">
			<option name="wxSP_3D"
				help="Draws a 3D effect border and sash." />
			<option name="wxSP_3DSASH"
				help="Draws a 3D effect sash (part of default style)." />
			<option name="wxSP_3DBORDER"
				help="Synonym for wxSP_BORDER." />
			<option name="wxSP_BORDER"
				help="Draws a standard border." />
			<option name="wxSP_NOBORDER"
				help="No border (default)." />
			<option name="wxSP_NOSASH"
				help="Sets the sash to be invisible, even when the window is split. This prevents the user to resize the windows." />
			<option name="wxSP_THIN_SASH"
				help="Draws a thin sash." />
			<option name="wxSP_NO_XP_THEME"
				help="Under Windows XP, switches off the attempt to draw the splitter using Windows XP theming, so the borders and sash will take on the pre-XP look." />
			<option name="wxSP_PERMIT_UNSPLIT"
				help="Always allow to unsplit, even with the minimum pane size other than zero. Note: The designer prevents un-splitting." />
			<option name="wxSP_LIVE_UPDATE"
				help="Don't draw XOR line but resize the child windows immediately." />
			wxSP_3D
		</property>
		<event name="wxEVT_SPLITTER_SASH_POS_CHANGING" class="wxSplitterEvent"
			help="The sash position is in the process of being changed. May be used to modify the position of the tracking bar to properly reflect the position that would be set if the drag were to be completed at this point." />
		<event name="wxEVT_SPLITTER_SASH_POS_CHANGED" class="wxSplitterEvent"
			help="The sash position was changed. May be used to modify the sash position before it is set, or to prevent the change from taking place." />
		<event name="wxEVT_SPLITTER_UNSPLIT" class="wxSplitterEvent"
			help="The splitter has been just unsplit." />
		<event name="wxEVT_SPLITTER_DOUBLECLICKED" class="wxSplitterEvent"
			help="The sash was double clicked. The default behaviour is to unsplit the window when this happens (unless the minimum pane size has been set to a value greater than zero)." />
	</gen>

	<gen class="wxScrolledCanvas" image="wxScrolledWindow" type="container">
		<inherits class="wxWindow">
			<property name="window_style" type="bitlist">wxHSCROLL | wxVSCROLL</property>
		</inherits>
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_scroll_canvas</property>
		<property name="scroll_rate_x" type="uint"
			help="Set the horizontal scrolling increment.">5</property>
		<property name="scroll_rate_y" type="uint"
			help="Set the vertical scrolling increment.">5</property>
		<event name="wxEVT_SCROLLWIN_TOP" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_BOTTOM" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_LINEUP" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_LINEDOWN" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_PAGEUP" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_PAGEDOWN" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_THUMBTRACK" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_THUMBRELEASE" class="wxScrollWinEvent" />
	</gen>

	<gen class="wxScrolledWindow" image="wxScrolledWindow" type="container">
		<inherits class="wxWindow">
			<property name="window_style" type="bitlist">wxHSCROLL | wxVSCROLL</property>
		</inherits>
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_scroll_panel</property>
		<property name="scroll_rate_x" type="uint"
			help="Set the horizontal scrolling increment.">5</property>
		<property name="scroll_rate_y" type="uint"
			help="Set the vertical scrolling increment.">5</property>
		<event name="wxEVT_SCROLLWIN_TOP" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_BOTTOM" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_LINEUP" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_LINEDOWN" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_PAGEUP" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_PAGEDOWN" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_THUMBTRACK" class="wxScrollWinEvent" />
		<event name="wxEVT_SCROLLWIN_THUMBRELEASE" class="wxScrollWinEvent" />
	</gen>

	<gen class="wxCollapsiblePane" image="wxCollapsiblePane" type="container">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_collapsible_pane</property>
		<property name="label" type="string_escapes">collapsible</property>
		<property name="collapsed" type="bool">0</property>
		<property name="style" type="bitlist">
			<option name="wxCP_DEFAULT_STYLE"
				help="The default style. It includes wxTAB_TRAVERSAL and wxBORDER_NONE." />
			<option name="wxCP_NO_TLW_RESIZE"
				help="By default wxCollapsiblePane resizes the top level window containing it when its own size changes. This allows you to implement dialogs containing an optionally shown part. Set this flag to disable the automatic resizing of the parent." />
			wxCP_DEFAULT_STYLE
		</property>
		<event name="wxEVT_COLLAPSIBLEPANE_CHANGED" class="wxCollapsiblePaneEvent"
			help="The user expanded or collapsed the collapsible pane." />
	</gen>
</GeneratorDefinitions>)===";

=== KeyWorksRW/wxUiEditor/src/xml/textctrls_xml.xml
inline const char* textctrls_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="wxStaticText" image="wxStaticText" type="widget">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="String Validator" />
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_staticText</property>
		<property name="label" type="string_edit_escapes">MyLabel</property>
		<property name="markup" type="bool"
			help="Simple markup can be used to apply different fonts or colours to different parts of the control label when supported. If markup is not supported by the control or platform, it is simply stripped and SetLabel() is used with the resulting string.\n\nSample: This is <i>italic</i> and this is <span fgcolor='red'>red</span>">0</property>
		<property name="wrap" type="int"
			help="Wraps the control's label so that each of its lines becomes at most this many pixels wide if possible (the lines are broken at words boundaries so it might not be the case if words are too long). If width is negative, no wrapping is done.">-1</property>
		<property name="style" type="bitlist">
			<option name="wxALIGN_LEFT"
				help="Align the text to the left." />
			<option name="wxALIGN_RIGHT"
				help="Align the text to the right." />
			<option name="wxALIGN_CENTER_HORIZONTAL"
				help="Center the text (horizontally)." />
			<option name="wxST_NO_AUTORESIZE"
				help="By default, the control will adjust its size to exactly fit to the size of the text when SetLabel() is called. If this style flag is given, the control will not change its size (this style is especially useful with controls which also have the wxALIGN_RIGHT or the wxALIGN_CENTER_HORIZONTAL style because otherwise they won't make sense any longer after a call to SetLabel())." />
			<option name="wxST_ELLIPSIZE_START"
				help="If the labeltext width exceeds the control width, replace the beginning of the label with an ellipsis; uses wxControl::Ellipsize." />
			<option name="wxST_ELLIPSIZE_MIDDLE"
				help="If the label text width exceeds the control width, replace the middle of the label with an ellipsis; uses wxControl::Ellipsize." />
			<option name="wxST_ELLIPSIZE_END"
				help="If the label text width exceeds the control width, replace the end of the label with an ellipsis; uses wxControl::Ellipsize." />
		</property>
	</gen>

	<gen class="wxTextCtrl" image="wxTextCtrl" type="widget">
		<inherits class="Text Validator" />
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<inherits class="sizer_child" />
	</gen>

	<gen class="wxRichTextCtrl" image="richtextctrl" type="widget">
		<inherits class="wxWindow">
			<property name="window_style" type="bitlist">wxVSCROLL|wxHSCROLL|wxWANTS_CHARS</property>
			<property name="minimum_size" type="wxSize"
				help="Sets the minimum size of the window, to indicate to the sizer layout mechanism that this is the minimum required size.">200,100d</property>
		</inherits>
		<inherits class="sizer_child" />
		<property name="var_name" type="string">m_richText</property>
		<property name="value" type="string_escapes"
			help="Sets the initial contents of the control." />
		<property name="hint" type="string_escapes"
			help="Sets a hint to be shown when the control is empty and does not have the focus." />
		<property name="style" type="bitlist">
			<option name="wxRE_CENTRE_CARET"
				help="The control will try to keep the caret line centred vertically while editing." />
			<option name="wxRE_READONLY"
				help="The text will not be editable." />
		</property>
		<property name="focus" type="bool"
			help="When checked, this control will be set to receive keyboard input when the parent form is first created.">0</property>
		<event name="wxEVT_TEXT" class="wxCommandEvent"
			help="Generated when the text changes. Notice that this event will always be sent when the text controls contents changes - whether this is due to user input or comes from the program itself (for example, if SetValue() is called)" />
		<event name="wxEVT_TEXT_ENTER" class="wxCommandEvent"
			help="Generated when enter is pressed in a text control (which must have wxTE_PROCESS_ENTER style for this event to be generated)." />
		<event name="wxEVT_TEXT_URL" class="wxTextUrlEvent"
			help="Generated when a mouse event occurrs over a URL in the text control (wxMSW and wxGTK2 only)" />

		<event name="wxEVT_RICHTEXT_LEFT_CLICK" class="wxRichTextEvent"
			help="Generated when the user releases the left mouse button over an object." />
		<event name="wxEVT_RICHTEXT_RIGHT_CLICK" class="wxRichTextEvent"
			help="Generated when the user releases the right mouse button over an object." />
		<event name="wxEVT_RICHTEXT_MIDDLE_CLICK" class="wxRichTextEvent"
			help="Generated when the user releases the middle mouse button over an object." />
		<event name="EVT_RICHTEXT_LEFT_DCLICK" class="wxRichTextEvent"
			help="Generated when the user double-clicks an object." />

		<event name="wxEVT_RICHTEXT_CHARACTER" class="wxRichTextEvent"
			help="Generated when the user presses a character key. Valid event functions: GetFlags, GetPosition, GetCharacter." />
		<event name="wxEVT_RICHTEXT_CONSUMING_CHARACTER" class="wxRichTextEvent"
			help="Generated when the user presses a character key but before it is processed and inserted into the control. Call Veto to prevent normal processing." />
		<event name="wxEVT_RICHTEXT_DELETE" class="wxRichTextEvent"
			help="Generated when the user presses the backspace or delete key. Valid event functions: GetFlags, GetPosition." />
		<event name="wxEVT_RICHTEXT_RETURN" class="wxRichTextEvent"
			help="Generated when the user presses the return key. Valid event functions: GetFlags, GetPosition." />

		<event name="wxEVT_RICHTEXT_STYLESHEET_CHANGING" class="wxRichTextEvent"
			help="Generated when the control's stylesheet is about to change." />
		<event name="wxEVT_RICHTEXT_STYLESHEET_CHANGED" class="wxRichTextEvent"
			help="Generated when the control's stylesheet has changed, for example the user added, edited or deleted a style. Valid event functions: GetRange, GetPosition." />
		<event name="wxEVT_RICHTEXT_STYLESHEET_REPLACING" class="wxRichTextEvent"
			help="Generated when the control's stylesheet is about to be replaced, for example when a file is loaded into the control. Valid event functions: Veto, GetOldStyleSheet, GetNewStyleSheet." />
		<event name="wxEVT_RICHTEXT_STYLESHEET_REPLACED" class="wxRichTextEvent"
			help="Generated when the control's stylesheet has been replaced, for example when a file is loaded into the control. Valid event functions: GetOldStyleSheet, GetNewStyleSheet." />

		<event name="wxEVT_RICHTEXT_PROPERTIES_CHANGED" class="wxRichTextEvent"
			help="Generated when properties have been applied to the control. Valid event functions: GetPosition, GetRange." />
		<event name="wxEVT_RICHTEXT_STYLE_CHANGED" class="wxRichTextEvent"
			help="Generated when styling has been applied to the control. Valid event functions: GetPosition, GetRange." />
		<event name="wxEVT_RICHTEXT_CONTENT_INSERTED" class="wxRichTextEvent"
			help="Generated when content has been inserted into the control. Valid event functions: GetPosition, GetRange." />
		<event name="wxEVT_RICHTEXT_CONTENT_DELETED" class="wxRichTextEvent"
			help="Generated when content has been deleted from the control. Valid event functions: GetPosition, GetRange." />
		<event name="wxEVT_RICHTEXT_BUFFER_RESET " class="wxRichTextEvent"
			help="Generated when the buffer has been reset by deleting all content. You can use this to set a default style for the first new paragraph." />
		<event name="wxEVT_RICHTEXT_SELECTION_CHANGED" class="wxRichTextEvent"
			help="Generated when the selection range has changed." />
		<event name="wxEVT_RICHTEXT_FOCUS_OBJECT_CHANGED" class="wxRichTextEvent"
			help="Generated when the current focus object has changed." />
	</gen>
</GeneratorDefinitions>)===";

=== KeyWorksRW/wxUiEditor/src/xml/wizard_xml.xml
inline const char* wizard_xml = R"===(<?xml version="1.0"?>
<!DOCTYPE GeneratorDefinitions SYSTEM "gen.dtd">
<GeneratorDefinitions>
	<gen class="wxWizard" image="wxWizard" type="wizard">
		<inherits class="C++ Settings" />
		<inherits class="C++ Derived Class Settings" />
		<inherits class="wxPython Settings" />
		<inherits class="XRC Settings" />
		<inherits class="wxTopLevelWindow" />
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<property name="class_name" type="string"
			help="The name of the base class.">MyWizardBase</property>
		<property name="title" type="string_escapes"
			help="The text to display on the Wizard's title bar." />
		<property name="style" type="bitlist">
			<option name="wxCAPTION"
				help="Puts a caption on the dialog box." />
			<option name="wxDEFAULT_DIALOG_STYLE"
				help="Equivalent to a combination of wxCAPTION, wxCLOSE_BOX and wxSYSTEM_MENU (the last one is not used under Unix)" />
			<option name="wxRESIZE_BORDER"
				help="Display a resizeable frame around the window." />
			<option name="wxSYSTEM_MENU"
				help="Display a system menu." />
			<option name="wxCLOSE_BOX"
				help="Displays a close box on the dialog." />
			<option name="wxMAXIMIZE_BOX"
				help="Displays a maximize box on the dialog." />
			<option name="wxMINIMIZE_BOX"
				help="Displays a minimize box on the dialog." />
			<option name="wxSTAY_ON_TOP"
				help="The dialog stays on top of all other windows." />
			<option name="wxDIALOG_NO_PARENT"
				help="By default, a dialog created with a NULL parent window will be given the application's top level window as parent. Use this style to prevent this from happening and create an orphan dialog. This is not recommended for modal dialogs." />
			wxDEFAULT_DIALOG_STYLE
		</property>
		<property name="extra_style" type="bitlist">
			<option name="wxWIZARD_EX_HELPBUTTON"
				help="Shows a Help button using wxID_HELP." />
		</property>
		<property name="border" type="int"
			help="Sets the width of the border around the page area." />
		<property name="center" type="option"
			help="Centers the dialog box on the display in the chosen direction.">
			<option name="" />
			<option name="wxHORIZONTAL" />
			<option name="wxVERTICAL" />
			<option name="wxBOTH" />
			wxBOTH
		</property>
		<property name="bitmap" type="image"
			help="Bitmap to display on the left side of the wizard (default: none)." />
		<property name="bmp_placement" type="bitlist">
			<option name="wxWIZARD_VALIGN_TOP"
				help="The bitmap is vertically aligned at the top." />
			<option name="wxWIZARD_VALIGN_CENTRE"
				help="The bitmap is centered vertically." />
			<option name="wxWIZARD_VALIGN_BOTTOM"
				help="The bitmap is vertically aligned at the bottom." />
			<option name="wxWIZARD_HALIGN_LEFT"
				help="The bitmap is horizontally aligned to the left." />
			<option name="wxWIZARD_HALIGN_CENTRE"
				help="The bitmap is horizontally aligned in the center." />
			<option name="wxWIZARD_HALIGN_RIGHT"
				help="The bitmap is horizontally aligned to the right." />
			<option name="wxWIZARD_TILE"
				help="The bitmap is tiled." />
		</property>
		<property name="bmp_min_width" type="int"
			help="Sets the minimum width for the bitmap that will be constructed to contain the actual wizard or page bitmap if a non-zero bitmap placement flag has been set. If this is not set when using bitmap placement, the initial layout may be incorrect.">-1</property>
		<property name="bmp_background_colour" type="wxColour"
			help="Sets the colour that should be used to fill the area not taken up by the wizard or page bitmap, if a non-zero bitmap placement flag has been set." />
		<event name="wxEVT_INIT_DIALOG" class="wxInitDialogEvent"
			help="Generated when the Wizard is being initialized." />
		<event name="wxEVT_WIZARD_PAGE_CHANGED" class="wxWizardEvent"
			help="This event cannot be vetoed." />
		<event name="wxEVT_WIZARD_PAGE_CHANGING" class="wxWizardEvent"
			help="This event can be vetoed." />
		<event name="wxEVT_WIZARD_BEFORE_PAGE_CHANGED" class="wxWizardEvent"
			help="Generated after Next is clicked but before GetNext is called. Unlike wxEVT_WIZARD_PAGE_CHANGING, the handler for this function can change state that might affect the return value of GetNext. This event can be vetoed." />
		<event name="wxEVT_WIZARD_PAGE_SHOWN" class="wxWizardEvent"
			help="The page was shown and laid out (this event cannot be vetoed)." />
		<event name="wxEVT_WIZARD_CANCEL" class="wxWizardEvent"
			help="The user attempted to cancel the wizard (this event may be vetoed)." />
		<event name="wxEVT_WIZARD_HELP" class="wxWizardEvent"
			help="Generated when the help button is pressed. " />
		<event name="wxEVT_WIZARD_FINISHED" class="wxWizardEvent"
			help="Generated when the finish button is pressed." />
	</gen>

	<gen class="wxWizardPageSimple" image="wxWizardPageSimple" type="wizardpagesimple">
		<inherits class="wxWindow" />
		<inherits class="Window Events" />
		<property name="var_name" type="string">wizPage</property>
		<property name="bitmap" type="image"
			help="Page-specific bitmap (default: none)." />
	</gen>
</GeneratorDefinitions>)===";
